### ISSUE TITLE
add station.in to template 

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/BayDeltaSCHISM#50]
for file copy way of doing it, which is simple but not very powerful:

```
copy_resources:
  - station.in

```

for a capability : 

```
station.in:
  clip_to_mesh: True        #  eliminate stations not in mesh. May not be desired in studies with different meshes
  requests:
     - all                             # type `$ station --help` from a schimpy-enabled  prompt for a list
  station_lists:
    - dms_datastore          #  magic keyword, but you could just use the provided file if you want stability over up-to-date
    - mystudy_station.in    # will append and renumber

```
